In [10]:
import pandas as pd
import numpy as np

data = {
    "A": [1, 2, 3, 4],
    "B": [10.5, 20.1, 30.2, 40.3],
    "C": ["x", "y", "z", "w"]
}

df = pd.DataFrame(data)
df

   A     B  C
0  1  10.5  x
1  2  20.1  y
2  3  30.2  z
3  4  40.3  w

## df.copy()

In [11]:
df_copy = df.copy()
df_copy["A"] = df_copy["A"] * 10

df
df_copy

    A     B  C
0  10  10.5  x
1  20  20.1  y
2  30  30.2  z
3  40  40.3  w

## pd.read_csv(chunksize)

In [12]:
for chunk in pd.read_csv(r"C:\Users\Hey!\OneDrive\Desktop\Pandas-for-Data-Science\dataset\countries of the world.csv", chunksize=2):
    print(chunk)

        Country                               Region
0  Afghanistan         ASIA (EX. NEAR EAST)
1      Albania   EASTERN EUROPE
           Country                               Region
2         Algeria   NORTHERN AFRICA
3  American Samoa   OCEANIA
    Country                               Region
4  Andorra   WESTERN EUROPE
5   Angola   SUB-SAHARAN AFRICA
              Country                   Region
6           Anguilla   LATIN AMER. & CARIB
7  Antigua & Barbuda   LATIN AMER. & CARIB
      Country                   Region
8  Argentina   LATIN AMER. & CARIB
9    Armenia      C.W. OF IND. STATES
       Country                               Region
10      Aruba               LATIN AMER. & CARIB
11  Australia   OCEANIA
        Country                               Region
12     Austria   WESTERN EUROPE
13  Azerbaijan                  C.W. OF IND. STATES
          Country                               Region
14  Bahamas, The               LATIN AMER. & CARIB
15       Bahrain   NEAR EAST
        Country                         Region
16  Bangladesh   ASIA (EX. NEAR EAST)
17    Barbados         LATIN AMER. & CARIB
     Country                               Region
18  Belarus                  C.W. OF IND. STATES
19  Belgium   WESTERN EUROPE
    Country                               Region
20  Belize               LATIN AMER. & CARIB
21   Benin   SUB-SAHARAN AFRICA
     Country                               Region
22  Bermuda   NORTHERN AMERICA
23   Bhutan         ASIA (EX. NEAR EAST)
                  Country                               Region
24               Bolivia               LATIN AMER. & CARIB
25  Bosnia & Herzegovina   EASTERN EUROPE
      Country                               Region
26  Botswana   SUB-SAHARAN AFRICA
27    Brazil               LATIN AMER. & CARIB
                Country                         Region
28  British Virgin Is.         LATIN AMER. & CARIB
29              Brunei   ASIA (EX. NEAR EAST)
          Country                               Region
30      Bulgaria   EASTERN EUROPE
31  Burkina Faso   SUB-SAHARAN AFRICA
     Country                               Region
32    Burma         ASIA (EX. NEAR EAST)
33  Burundi   SUB-SAHARAN AFRICA
      Country                               Region
34  Cambodia         ASIA (EX. NEAR EAST)
35  Cameroon   SUB-SAHARAN AFRICA
        Country                               Region
36      Canada   NORTHERN AMERICA
37  Cape Verde   SUB-SAHARAN AFRICA
                  Country                               Region
38        Cayman Islands               LATIN AMER. & CARIB
39  Central African Rep.   SUB-SAHARAN AFRICA
   Country                               Region
40   Chad   SUB-SAHARAN AFRICA
41  Chile               LATIN AMER. & CARIB
      Country                         Region
42     China   ASIA (EX. NEAR EAST)
43  Colombia         LATIN AMER. & CARIB
              Country                               Region
44           Comoros   SUB-SAHARAN AFRICA
45  Congo, Dem. Rep.   SUB-SAHARAN AFRICA
                  Country                               Region
46  Congo, Repub. of the   SUB-SAHARAN AFRICA
47          Cook Islands   OCEANIA
           Country                               Region
48     Costa Rica               LATIN AMER. & CARIB
49  Cote d'Ivoire   SUB-SAHARAN AFRICA
     Country                               Region
50  Croatia   EASTERN EUROPE
51     Cuba               LATIN AMER. & CARIB
            Country                               Region
52          Cyprus   NEAR EAST
53  Czech Republic   EASTERN EUROPE
      Country                               Region
54   Denmark   WESTERN EUROPE
55  Djibouti   SUB-SAHARAN AFRICA
                Country                   Region
56            Dominica   LATIN AMER. & CARIB
57  Dominican Republic   LATIN AMER. & CARIB
        Country                         Region
58  East Timor   ASIA (EX. NEAR EAST)
59     Ecuador         LATIN AMER. & CARIB
         Country                               Region
60        Egypt   NORTHERN AFRICA
61  El Salvador               LATIN AMER. & CARIB
               Country                               Region
62  Equatorial Guinea   SUB-SAHARAN AFRICA
63            Eritrea   SUB-SAHARAN AFRICA
      Country                               Region
64   Estonia   BALTICS
65  Ethiopia   SUB-SAHARAN AFRICA
           Country                               Region
66  Faroe Islands   WESTERN EUROPE
67           Fiji   OCEANIA
     Country                               Region
68  Finland   WESTERN EUROPE
69   France   WESTERN EUROPE
              Country                               Region
70     French Guiana               LATIN AMER. & CARIB
71  French Polynesia   OCEANIA
         Country                               Region
72        Gabon   SUB-SAHARAN AFRICA
73  Gambia, The   SUB-SAHARAN AFRICA
        Country                               Region
74  Gaza Strip   NEAR EAST
75     Georgia                  C.W. OF IND. STATES
     Country                               Region
76  Germany   WESTERN EUROPE
77    Ghana   SUB-SAHARAN AFRICA
       Country                               Region
78  Gibraltar   WESTERN EUROPE
79     Greece   WESTERN EUROPE
       Country                               Region
80  Greenland   NORTHERN AMERICA
81    Grenada               LATIN AMER. & CARIB
        Country                               Region
82  Guadeloupe               LATIN AMER. & CARIB
83        Guam   OCEANIA
       Country                               Region
84  Guatemala               LATIN AMER. & CARIB
85   Guernsey   WESTERN EUROPE
           Country                               Region
86         Guinea   SUB-SAHARAN AFRICA
87  Guinea-Bissau   SUB-SAHARAN AFRICA
    Country                   Region
88  Guyana   LATIN AMER. & CARIB
89   Haiti   LATIN AMER. & CARIB
       Country                         Region
90   Honduras         LATIN AMER. & CARIB
91  Hong Kong   ASIA (EX. NEAR EAST)
     Country                               Region
92  Hungary   EASTERN EUROPE
93  Iceland   WESTERN EUROPE
       Country                         Region
94      India   ASIA (EX. NEAR EAST)
95  Indonesia   ASIA (EX. NEAR EAST)
   Country                               Region
96   Iran         ASIA (EX. NEAR EAST)
97   Iraq   NEAR EAST
         Country                               Region
98      Ireland   WESTERN EUROPE
99  Isle of Man   WESTERN EUROPE
     Country                               Region
100  Israel   NEAR EAST
101   Italy   WESTERN EUROPE
      Country                         Region
102  Jamaica         LATIN AMER. & CARIB
103    Japan   ASIA (EX. NEAR EAST)
     Country                               Region
104  Jersey   WESTERN EUROPE
105  Jordan   NEAR EAST
         Country                               Region
106  Kazakhstan                  C.W. OF IND. STATES
107       Kenya   SUB-SAHARAN AFRICA
           Country                               Region
108      Kiribati   OCEANIA
109  Korea, North         ASIA (EX. NEAR EAST)
           Country                               Region
110  Korea, South         ASIA (EX. NEAR EAST)
111        Kuwait   NEAR EAST
         Country                         Region
112  Kyrgyzstan            C.W. OF IND. STATES
113        Laos   ASIA (EX. NEAR EAST)
      Country                               Region
114   Latvia   BALTICS
115  Lebanon   NEAR EAST
      Country                               Region
116  Lesotho   SUB-SAHARAN AFRICA
117  Liberia   SUB-SAHARAN AFRICA
            Country                               Region
118          Libya   NORTHERN AFRICA
119  Liechtenstein   WESTERN EUROPE
         Country                               Region
120   Lithuania   BALTICS
121  Luxembourg   WESTERN EUROPE
        Country                               Region
122      Macau         ASIA (EX. NEAR EAST)
123  Macedonia   EASTERN EUROPE
         Country                               Region
124  Madagascar   SUB-SAHARAN AFRICA
125      Malawi   SUB-SAHARAN AFRICA
       Country                         Region
126  Malaysia   ASIA (EX. NEAR EAST)
127  Maldives   ASIA (EX. NEAR EAST)
    Country                               Region
128   Mali   SUB-SAHARAN AFRICA
129  Malta   WESTERN EUROPE
               Country                               Region
130  Marshall Islands   OCEANIA
131        Martinique               LATIN AMER. & CARIB
         Country                               Region
132  Mauritania   SUB-SAHARAN AFRICA
133   Mauritius   SUB-SAHARAN AFRICA
      Country                               Region
134  Mayotte   SUB-SAHARAN AFRICA
135   Mexico               LATIN AMER. & CARIB
                   Country                               Region
136  Micronesia, Fed. St.   OCEANIA
137               Moldova                  C.W. OF IND. STATES
       Country                               Region
138    Monaco   WESTERN EUROPE
139  Mongolia         ASIA (EX. NEAR EAST)
         Country                               Region
140  Montserrat               LATIN AMER. & CARIB
141     Morocco   NORTHERN AFRICA
         Country                               Region
142  Mozambique   SUB-SAHARAN AFRICA
143     Namibia   SUB-SAHARAN AFRICA
    Country                               Region
144  Nauru   OCEANIA
145  Nepal         ASIA (EX. NEAR EAST)
                   Country                               Region
146           Netherlands   WESTERN EUROPE
147  Netherlands Antilles               LATIN AMER. & CARIB
            Country                               Region
148  New Caledonia   OCEANIA
149    New Zealand   OCEANIA
        Country                               Region
150  Nicaragua               LATIN AMER. & CARIB
151      Niger   SUB-SAHARAN AFRICA
                 Country                               Region
152             Nigeria   SUB-SAHARAN AFRICA
153  N. Mariana Islands   OCEANIA
     Country                               Region
154  Norway   WESTERN EUROPE
155    Oman   NEAR EAST
       Country                               Region
156  Pakistan         ASIA (EX. NEAR EAST)
157     Palau   OCEANIA
               Country                               Region
158            Panama               LATIN AMER. & CARIB
159  Papua New Guinea   OCEANIA
       Country                   Region
160  Paraguay   LATIN AMER. & CARIB
161      Peru   LATIN AMER. & CARIB
          Country                               Region
162  Philippines         ASIA (EX. NEAR EAST)
163       Poland   EASTERN EUROPE
          Country                               Region
164     Portugal   WESTERN EUROPE
165  Puerto Rico               LATIN AMER. & CARIB
      Country                               Region
166    Qatar   NEAR EAST
167  Reunion   SUB-SAHARAN AFRICA
      Country                               Region
168  Romania   EASTERN EUROPE
169   Russia                  C.W. OF IND. STATES
           Country                               Region
170        Rwanda   SUB-SAHARAN AFRICA
171  Saint Helena   SUB-SAHARAN AFRICA
                  Country                   Region
172  Saint Kitts & Nevis   LATIN AMER. & CARIB
173          Saint Lucia   LATIN AMER. & CARIB
                               Country                               Region
174              St Pierre & Miquelon   NORTHERN AMERICA
175  Saint Vincent and the Grenadines               LATIN AMER. & CARIB
         Country                               Region
176       Samoa   OCEANIA
177  San Marino   WESTERN EUROPE
                  Country                               Region
178  Sao Tome & Principe   SUB-SAHARAN AFRICA
179         Saudi Arabia   NEAR EAST
      Country                               Region
180  Senegal   SUB-SAHARAN AFRICA
181   Serbia   EASTERN EUROPE
           Country                               Region
182    Seychelles   SUB-SAHARAN AFRICA
183  Sierra Leone   SUB-SAHARAN AFRICA
        Country                               Region
184  Singapore         ASIA (EX. NEAR EAST)
185   Slovakia   EASTERN EUROPE
              Country                               Region
186         Slovenia   EASTERN EUROPE
187  Solomon Islands   OCEANIA
           Country                               Region
188       Somalia   SUB-SAHARAN AFRICA
189  South Africa   SUB-SAHARAN AFRICA
        Country                               Region
190      Spain   WESTERN EUROPE
191  Sri Lanka         ASIA (EX. NEAR EAST)
       Country                               Region
192     Sudan   SUB-SAHARAN AFRICA
193  Suriname               LATIN AMER. & CARIB
        Country                               Region
194  Swaziland   SUB-SAHARAN AFRICA
195     Sweden   WESTERN EUROPE
          Country                               Region
196  Switzerland   WESTERN EUROPE
197        Syria   NEAR EAST
         Country                         Region
198      Taiwan   ASIA (EX. NEAR EAST)
199  Tajikistan            C.W. OF IND. STATES
       Country                               Region
200  Tanzania   SUB-SAHARAN AFRICA
201  Thailand         ASIA (EX. NEAR EAST)
    Country                               Region
202   Togo   SUB-SAHARAN AFRICA
203  Tonga   OCEANIA
                Country                               Region
204  Trinidad & Tobago               LATIN AMER. & CARIB
205            Tunisia   NORTHERN AFRICA
           Country                               Region
206        Turkey   NEAR EAST
207  Turkmenistan                  C.W. OF IND. STATES
                Country                               Region
208  Turks & Caicos Is               LATIN AMER. & CARIB
209             Tuvalu   OCEANIA
      Country                               Region
210   Uganda   SUB-SAHARAN AFRICA
211  Ukraine                  C.W. OF IND. STATES
                   Country                               Region
212  United Arab Emirates   NEAR EAST
213        United Kingdom   WESTERN EUROPE
            Country                               Region
214  United States   NORTHERN AMERICA
215        Uruguay               LATIN AMER. & CARIB
         Country                               Region
216  Uzbekistan                  C.W. OF IND. STATES
217     Vanuatu   OCEANIA
        Country                         Region
218  Venezuela         LATIN AMER. & CARIB
219    Vietnam   ASIA (EX. NEAR EAST)
                Country                               Region
220     Virgin Islands               LATIN AMER. & CARIB
221  Wallis and Futuna   OCEANIA
             Country                               Region
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
     Country                               Region
224   Yemen   NEAR EAST
225  Zambia   SUB-SAHARAN AFRICA
       Country                               Region
226  Zimbabwe   SUB-SAHARAN AFRICA

## df.select_dtypes()

In [13]:
# Select numeric columns
df.select_dtypes(include=["number"])

# Select object (string) columns
df.select_dtypes(include=["object"])

C:\Users\Hey!\AppData\Local\Temp\ipykernel_9744\2046934436.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=["object"])

   C
0  x
1  y
2  z
3  w

## df.convert_dtypes()

In [14]:
df_converted = df.convert_dtypes()
df_converted.dtypes

A      Int64
B    Float64
C     string
dtype: object